apiVersion: v1
kind: pod
metadat: 
  name: task-pv-pod
containers: 
  - name: task-pv-container
    image: nginx
    ports: 
      - containerPort: 80
        name: "http-server"
      volumeMounts:
        - mountpath: "/usr/share/nginx/html"
          name: task-pv-storage